### ISSUE TITLE
Producer not working anymore 

### ISSUE THREAD

**Issue by nazaroid** [tarantool/kafka#29]
**precondition: FROM tarantool/tarantool:2.6.1**

1. If you install the plugin (tarantoolctl rocks install) and run the producer, then an error occurs on sending messages:
`
2020-12-05 17:31:00.120 [1] main/132/lua C> fiber 132 is switched while running GC finalizer (i.e. __gc metamethod)
2020-12-05 17:31:00.120 [1] main/132/lua C> #2 poll_msg (method), [C]:-1
2020-12-05 17:31:00.120 [1] main/132/lua C> #3 _poll_msg (method), /opt/tarantool/kafka/init.lua:66
2020-12-05 17:31:00.120 [1] main/132/lua C> #4 (null) (), /opt/tarantool/kafka/init.lua:27
`
2. As pointed earlier (see https://github.com/tarantool/kafka/issues/26), tests are falling. The reason for the crash is that static linking of sasl library does not work. If you disable the use of sasl (kafka \ CMakeLists.txt -> ./configure --disable-sasl), then linking problem disappears and problem from point 1 is reproduced. (see docker logs -f kafka-test)

**Comment by olegrok** [comment]
This leads because "consumer_destroy" yields https://github.com/tarantool/kafka/blob/7fe2a094259023ed8e825f7deebc0f1c277d1c93/kafka/consumer.c#L534-L537

For details see (https://github.com/tarantool/tarantool/issues/4518#issuecomment-704259323).

Workaround is call consumer_destroy by hand to prevent calling `__gc` machinery.

**Comment by nazaroid** [comment]
Workaround  does not work. The call 'producer:destroy_producer()' just hangs...

**Comment by nazaroid** [comment]
How implement this workaround without building custom tarantool/kafka plugin?

**Comment by RepentantGopher** [comment]
Should be fixed in https://github.com/tarantool/kafka/pull/30

**Comment by RepentantGopher** [comment]
Fixes was released in 1.3.0 version https://github.com/tarantool/kafka/releases/tag/1.3.0
