### ISSUE TITLE
Add connetction check support

### ISSUE THREAD

**Issue by amitichev** [tarantool/kafka#59]
Good day, team!
There is a requirement in our side projects to provide the availability to check Kafka connection on preprocessing.
So, let's export a few methods from librdkafka?
The functions that we need is:
 - [ ] rd_kafka_metadata
 - [ ] rd_kafka_list_groups
 - [ ] rd_kafka_conf_set_ssl_cert_verify_cb

**Comment by olegrok** [comment]
>  rd_kafka_conf_set_ssl_cert_verify_cb

I guess you don't actually need it. This callback is needed to provide custom certificate validation function. AFAIU it doesn't help with connection check support.

Also it should return status code (is validation successful or not) but it doesn't conform current kafka module architecture and will require significant rework.

**Comment by artur-barsegyan** [comment]
Close it, it's done
